### ISSUE TITLE
SNYK: Ensure Diagnostic Setting captures appropriate categories

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-azurerm-synapse#10]
### Summary of issues
- Number of issues: 1
- Severity: low
- Ensure Diagnostic Setting captures appropriate categories

[Link](https://security.snyk.io/rules/cloud/SNYK-CC-AZURE-552?_gl=1%2a1lh1wj6%2a_ga%2aMjAzNTIwMTA5LjE2NzY4OTUxOTQ.%2a_ga_X9SH3KP7B4%2aMTcwMDU2OTU3MS45LjEuMTcwMDU3NTMwMy4wLjAuMA..
) to issue in SNYK

### How to fix
- Set log blocks for the categories `Administrative,Alert,Policy,Security` with `enabled` set to `true` for each

### References
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#category
- https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-manager-diagnostic-settings

**Comment by hknutsen** [comment]
These are subscription-level log categories. Can be ignored.
